version: '3.8'

services:
  ml_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml_app
    ports:
      - "5000:5000"  # Expose le port 5000 de l'application
    volumes:
      - .:/app  # Monte le répertoire courant dans /app pour le développement
    environment:
      - PYTHONUNBUFFERED=1
    command: python3 src/main.py --train-data data/train.csv --test data/test.csv --train
