version: '3.8'

services:
    mlflow:
    build: .
    container_name: mlflow2
    restart: always
    ports:
      - "5003:5000"  # Expose MLflow UI on port 5002
    environment:
      - MLFLOW_TRACKING_URI=postgresql://mlflow_user:zeyneb@localhost:5432/mlflow_db2
    volumes:
      - ./mlflow_artifacts2:/mlflow/artifacts

